{% set name = "wavyopen" %}
{% set version = "0.4.2" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 274149ab28dd3699cf08880c9582416d4f26cd95899eeec6481fe7f21fd4cc0f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  entry_points:
    - wavyDownload = wavy.apps.wavyDownload:main
    - wavyCFG = wavy.apps.wavyCFG:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - matplotlib-base >=3.5
    - numpy >=1.20
    - scipy >=1.9
    - netcdf4 >=1.6
    - pyyaml >=6
    - cmocean >=3
    - joblib >=1.4
    - pandas >=2.2
    - xarray >=2024
    - pyresample >=1.30
    - geojson >=2.5
    - cartopy >=0.20
    - pygam >=0.9
    - roaring-landmask >=0.10
    - copernicusmarine >=2.0
    - xdg
    - tqdm >=4
    - python-dotenv
    - click
    - scikit-learn >=1.6
    - yapf

test:
  imports:
    - wavy
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/bohlinger/wavy
  summary: 'A package for processing/calibrating/validating wave measurements and wave model output.'
  description: A package for processing/calibrating/validating wave measurements and wave model output.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://wavyopen.readthedocs.io
  dev_url: https://github.com/bohlinger/wavy

extra:
  recipe-maintainers:
    - bohlinger
    - gauteh
